### PR TITLE
Do not setText for TextView in worker thread

### LINKED ISSUE #206: "Accessibility content change on non-UI thread"
## Description

Error is thrown while Text-to-Speech is speaking:

```java
2025-04-16 16:38:32.483 19458-19599 ViewRootImpl            ai.elimu.vitabu.debug                E  Accessibility content change on non-UI thread. Future Android versions will throw an exception.
                                                                                                    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                                                    	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:13361)
                                                                                                    	at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:11935)
                                                                                                    	at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:12138)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3935)
                                                                                                    	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:15914)
                                                                                                    	at android.widget.TextView.setText(TextView.java:7538)
                                                                                                    	at android.widget.TextView.setText(TextView.java:7341)
                                                                                                    	at android.widget.TextView.setText(TextView.java:7279)
                                                                                                    	at ai.elimu.vitabu.ui.storybook.CoverFragment$getUtteranceProgressListener$1.onRangeStart(CoverFragment.kt:113)
                                                                                                    	at android.speech.tts.TextToSpeech$Connection$1.onRangeStart(TextToSpeech.java:2279)
                                                                                                    	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:263)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1523)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1457)
```

This happens on Android API 35.

How to reproduce: Launch the app on Android API 35 and press the play button in any of the pages of a storybook.

## Why?

"Future Android versions will throw an exception."

---

> elimu.ai's mission is to build innovative learning software that empowers out-of-school children to teach themselves basic reading📖, writing✍🏽 and math🔢 **within 6 months**.

### PR DESCRIPTION
**Pull request by tuancoltech**
### Issue Number
* Resolves #206 

### Purpose
Do not setText for TextView in worker thread 

### Regression Tests

- [x] I tested my changes on Android 15 (API 35)
- [ ] I tested my changes on Android 14 (API 34)
- [ ] I tested my changes on Android 13 (API 33)
- [ ] I tested my changes on Android 12L (API 32)
- [ ] I tested my changes on Android 12 (API 31)
- [ ] I tested my changes on Android 11 (API 30)
- [ ] I tested my changes on Android 10 (API 29)
- [ ] I tested my changes on Android 9 (API 28)
- [ ] I tested my changes on Android 8.1 (API 27)
- [ ] I tested my changes on Android 8.0 (API 26)

#### UI Tests

- [x] I tested my changes on a 6-7" screen (▯ portrait orientation)
- [ ] I tested my changes on a 6-7" screen (▭ landscape orientation)
- [ ] I tested my changes on a 7-8" screen (▯ portrait orientation)
- [ ] I tested my changes on a 7-8" screen (▭ landscape orientation)
- [ ] I tested my changes on a 9-10" screen (▯ portrait orientation)
- [ ] I tested my changes on a 9-10" screen (▭ landscape orientation)

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved reliability of text highlighting during speech playback to ensure smooth and consistent UI updates.
  - Enhanced UI responsiveness by updating text and background highlights asynchronously during speech narration.

### CODE REVIEW

File: app/src/main/java/ai/elimu/vitabu/ui/storybook/CoverFragment.kt [hunk 1]
```diff
@@ -14,6 +14,9 @@ import android.view.View
 import android.view.ViewGroup
 import android.widget.TextView
 import androidx.core.content.ContextCompat
+import kotlinx.coroutines.CoroutineScope
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.launch
 import java.util.Collections
 
 class CoverFragment : ChapterFragment() {
```
Comment (jo-elimu) [inline app/src/main/java/ai/elimu/vitabu/ui/storybook/CoverFragment.kt:22]: @tuancoltech I'm not seeing the error messages anymore when using the Text-to-Speech with the book's cover page. But there are also errors in the `ChapterFragment`:

```kotlin
2025-04-16 23:44:39.578 16460-16688 ChapterFragment         ai.elimu.vitabu.debug                I  utteranceId: 0, start: 6, end: 10
2025-04-16 23:44:39.583 16460-16688 ViewRootImpl            ai.elimu.vitabu.debug                E  Accessibility content change on non-UI thread. Future Android versions will throw an exception.
                                                                                                    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                                                    	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:12504)
                                                                                                    	at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:11121)
                                                                                                    	at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:11324)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3908)
                                                                                                    	at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:15807)
                                                                                                    	at android.view.ViewGroup.notifySubtreeAccessibilityStateChangedIfNeeded(ViewGroup.java:3932)
                                                                                                    	at android.view.View.invalidateOutline(View.java:20181)
                                                                                                    	at android.view.View.setBackgroundDrawable(View.java:26488)
                                                                                                    	at android.view.View.setBackground(View.java:26373)
                                                                                                    	at ai.elimu.vitabu.ui.storybook.ChapterFragment$getUtteranceProgressListener$1.onRangeStart(ChapterFragment.kt:242)
                                                                                                    	at android.speech.tts.TextToSpeech$Connection$1.onRangeStart(TextToSpeech.java:2279)
                                                                                                    	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:263)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1512)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1451)
```

Will the fix you implemented in the `CoverFragment` be needed in the `ChapterFragment` as well?

Comment (tuancoltech) [reply app/src/main/java/ai/elimu/vitabu/ui/storybook/CoverFragment.kt:22]: @jo-elimu Yes, I've fixed the same issue with the same approach in `ChapterFragment`.
